### ISSUE TITLE
Got Keyerror when training the EAMOUT model and questions about one-to-many decoding

### ISSUE THREAD

**Issue by Ruby-G0** [ghchen18/cdalign#7]
First of all, Your work is very impressive. 😀
I encountered some problems during reproducing and would like to get some help.

**① I got Keyerror when training the EAMOUT model** on the preprocessed alignment dataset.
I used a NVIDIA-V100 and the environment settings are as follows:
fairseq                   0.9.0
torch                     1.11.0
Any idea about the error?
~~~txt
Traceback (most recent call last):
  File "/cdaAlign/cdalign-main/train.py", line 337, in <module>
    cli_main()
  File "/cdaAlign/cdalign-main/train.py", line 333, in cli_main
    main(args)
  File "/cdaAlign/cdalign-main/train.py", line 93, in main
    train(args, trainer, task, epoch_itr)
  File "/cdaAlign/cdalign-main/train.py", line 132, in train
    for i, samples in enumerate(progress, start=epoch_itr.iterations_in_epoch):
  File "/cdaAlign/cdalign-main/fairseq/progress_bar.py", line 181, in __iter__
    for i, obj in enumerate(self.iterable, start=self.offset):
  File "/cdaAlign/cdalign-main/fairseq/data/iterators.py", line 314, in __next__
    chunk.append(next(self.itr))
  File "/cdaAlign/cdalign-main/fairseq/data/iterators.py", line 43, in __next__
    return next(self.itr)
  File "/cdaAlign/cdalign-main/fairseq/data/iterators.py", line 36, in __iter__
    for x in self.iterable:
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/envs/cda-align/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/envs/cda-align/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cdaAlign/cdalign-main/fairseq/data/language_pair_dataset.py", line 215, in __getitem__
    example['alignment'] = self.align_dataset[index]
  File "/cdaAlign/cdalign-main/fairseq/data/indexed_dataset.py", line 222, in __getitem__
    ptx = self.cache_index[i]
KeyError: 2206735
~~~
**② In the one-to-many decoding experiment**, I tried to make the model to select the constraint candidate as mentioned in your paper, which I quote here.   
> the model runs another decoder forward pass and selects the constraint with the highest length-averaged log-probability as the target constraint. 

Does it means to:
 1. Use the max probability as the probability for target constraint tokens ;
 2. Calculate the score similarly as beamsearch with beam_size 1?

My implementations are simplified as follows. And I got a CSR score Lower than decoding without constraint. I would really appreciate your help with locating my mistake.
~~~python
# lprobs is the original probability distribution of current step
cur_max_prob =  lprobs[idx, :].max().clone()
# tgt_p_toks is a list of current target constraint candidate tokens
tmp_cons_prob = cur_max_prob * len(tgt_p_toks)
# append a candidate target constraint after the original hypothesis
# run another decoder forward pass after the new hypothesis
# and I got cur_lprobs,  the new probability distribution 
cur_score = (cur_lprobs.max().clone() + tmp_cons_prob + scores.view(bsz*beam_size, -1)[idx, step-1]) / int(step + len(tgt_p_toks) + 1)
~~~

**Comment by ghchen18** [comment]
thank you for your interest in our work. I am a little busy these days, so only give a simple reply. 

(1) as the first problem, maybe the alignment binarized data is missing. how do you binarize the alignment data? Here is an [example](https://github.com/facebookresearch/fairseq/tree/v0.9.0/examples/joint_alignment_translation), see step 3. 

(2) at certain time step, for certain hypothesis, when it aligns to a source constraint, then force the generation of target constraints ( each candidate may contain several tokens). With the decoder forward process, you can get the probabilities of each target constraint candidate, then use the averaged probability to select the constraint candidate.

**Comment by Ruby-G0** [comment]
> thank you for your interest in our work. I am a little busy these days, so only give a simple reply.
> 
> (1) as the first problem, maybe the alignment binarized data is missing. how do you binarize the alignment data? Here is an [example](https://github.com/facebookresearch/fairseq/tree/v0.9.0/examples/joint_alignment_translation), see step 3.
> 
> (2) at certain time step, for certain hypothesis, when it aligns to a source constraint, then force the generation of target constraints ( each candidate may contain several tokens). With the decoder forward process, you can get the probabilities of each target constraint candidate, then use the averaged probability to select the constraint candidate.

Sorry for my late update. Just want to inform you that I reproduced the result with the help of your detailed explanation. So my mistake is that I tried to generate all tokens in target constraints within one force generation run. Now I changed my code. During constraint selection, it generate only one token within one force generation run. And it performs well!
Thank you for the help!
